In [1]:
import numpy as np

In [2]:
data =[
    [0, 2],
    [2, 6],
    [1, 4],
    [2, 5],
    [-1, -1]
]

In [3]:
cov = np.cov(data)

In [4]:
cov

array([[ 2. ,  4. ,  3. ,  3. ,  0. ],
       [ 4. ,  8. ,  6. ,  6. ,  0. ],
       [ 3. ,  6. ,  4.5,  4.5,  0. ],
       [ 3. ,  6. ,  4.5,  4.5,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ]])

In [6]:
eigval, eigvec = np.linalg.eig(cov)

In [7]:
eigval

array([  3.55271368e-15,   1.90000000e+01,   1.21857074e-15,
         0.00000000e+00,   0.00000000e+00])

In [8]:
eigvec

array([[ -9.45905303e-01,   3.24442842e-01,  -1.67258257e-01,
          1.70359396e-17,   0.00000000e+00],
       [  2.22565954e-01,   6.48885685e-01,   7.55496554e-01,
         -4.00845638e-18,   0.00000000e+00],
       [  1.66924465e-01,   4.86664263e-01,  -4.47911617e-01,
         -7.07106781e-01,   0.00000000e+00],
       [  1.66924465e-01,   4.86664263e-01,  -4.47911617e-01,
          7.07106781e-01,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   1.00000000e+00]])