In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import numpy as np
import random
sns.set_style('white')

%matplotlib inline

In [2]:
movie_df = pd.read_csv('imdb.csv', delimiter='\t')

In [3]:
movie_df_sample = movie_df.sample(50)

In [8]:
data = np.arange(1,50+1)

In [9]:
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [10]:
len(data)

50

In [13]:
sample = np.random.choice(data, 50, replace=True)

In [14]:
len(sample)

50

In [15]:
sample

array([39, 41,  3, 29, 32, 10, 44,  6, 38, 26,  3, 28, 38, 20, 27, 45, 31,
        3, 49, 47, 11, 48, 34, 42, 16,  7, 12, 27, 14, 48, 43, 44, 49, 42,
       49, 46, 35, 27, 50,  3, 15,  4, 43, 45, 20, 46, 35, 11, 13, 31])

In [20]:
np.sort(sample)

array([ 3,  3,  3,  3,  4,  6,  7, 10, 11, 11, 12, 13, 14, 15, 16, 20, 20,
       26, 27, 27, 27, 28, 29, 31, 31, 32, 34, 35, 35, 38, 38, 39, 41, 42,
       42, 43, 43, 44, 44, 45, 45, 46, 46, 47, 48, 48, 49, 49, 49, 50])

In [21]:
np.mean(data)

25.5

In [22]:
np.mean(sample)

29.379999999999999

In [24]:
l = []

In [25]:
l.append(1)

In [26]:
l.append(2)

In [27]:
l

[1, 2]